---
name: Pipeline

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    strategy:
      max-parallel: 4
      matrix:
        java-version: ["23"]

    steps:
      - uses: step-security/harden-runner@v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4.5.0
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "corretto"
      - uses: gradle/actions/setup-gradle@v4.1.0

      - run: ./gradlew test
